### PR TITLE
Test on 3.5 and 3.6, stop testing 3.3

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by cclauss** [comment]
Looks great!!

**Comment by jonparrott** [comment]
@lukesneeringer @landrito or @bjwatson mind taking a look?

**Comment by lukesneeringer** [comment]
_Much_ better. Thank you for actually telling Travis to run the versions separately rather than relying on tox.

**Comment by jonparrott** [comment]
> Much better. Thank you for actually telling Travis to run the versions separately rather than relying on tox.

For sure, there's a lot of TLC this repo needs. I'm mostly just porting best practices over from google-auth.

Thanks for taking a look.

**Pull request merged**
