### PR TITLE
Make sure state is validated and correct user info is used.

### PR DESCRIPTION
**Pull request by bobvoorneveld**
Also removed import statements that are not being used anymore in the
views.

### CODE REVIEW

**Comment by bobvoorneveld** [comment]
I signed it!

**Comment by nathanielmanistaatgoogle** [comment]
What hope is there for test coverage for this change?

**Comment by bobvoorneveld** [comment]
There is no tests at all at the moment for this part of the sample. It seems to me there is a lot of work to be done before I can write a simple testcase for this little bug...

**Comment by jonparrott** [comment]
@bobvoorneveld I'm closing this PR due to inactivity. If you're still interested in getting this merged please let us know and we'll be happy to re-open it.

**Pull request closed without merging**
