### PR TITLE
Fix file stream recognition for Python 3

### PR DESCRIPTION
**Pull request by e00E**

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
We dropped support for Python 2.5 and earlier a long time ago, and even Python 2.6 is ancient history these days (http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html). Why not just drop the version check entirely?

**Comment by e00E** [comment]
Complementary bug: #142 

I dont know which versions you want to offically support but I do think it is reasonable to drop support for python < 2.6.

**Comment by e00E** [comment]
Complementary bug: #142 

I dont know which versions you want to offically support but I do think it is reasonable to drop support for python < 2.6.

**Comment by nathanielmanistaatgoogle** [comment]
Yeah. Let's just drop the version check entirely.

**Comment by e00E** [comment]
Hm it says Travis build failed, but the link only shows `There was an error while loading data, please try again`. I didnt test the last commit because I could not immediately figure out how to run the tests in the repository.

**Comment by nathanielmanistaatgoogle** [comment]
When I look at https://travis-ci.org/google/google-api-python-client/jobs/84685349 I see
```
======================================================================
ERROR: test_resumable_media_handle_uploads_of_unknown_size (tests.test_discovery.Discovery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/google/google-api-python-client/tests/test_discovery.py", line 1066, in test_resumable_media_handle_uploads_of_unknown_size
    status, body = request.next_chunk(http=http)
  File "/home/travis/build/google/google-api-python-client/.tox/py27/lib/python2.7/site-packages/oauth2client/util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/travis/build/google/google-api-python-client/googleapiclient/http.py", line 830, in next_chunk
    data = self.resumable.stream()
  File "/home/travis/build/google/google-api-python-client/googleapiclient/http.py", line 208, in stream
    raise NotImplementedError()
NotImplementedError: 
-------------------- >> begin captured logging << --------------------
googleapiclient.discovery: INFO: URL being requested: POST https://www.googleapis.com/upload/zoo/v1/animals?alt=json&uploadType=resumable
--------------------- >> end captured logging << ---------------------
```
. Could that be a consequence of this change?

**Comment by e00E** [comment]
Yes it was my fault. I should have just deleted the python version checks and kept everything else intact but I thought the whole if-else block was obsolete.

**Comment by e00E** [comment]
Unless there is a test running on python < 2.6 im not sure why it would fail. The diff to master is now very simple again, but we cant go through the "you tell me the error message and I fix it" cycle every time as the Travis links are still broken for me.

**Comment by e00E** [comment]
OH this is related to my browser somehow. I just tried a different one and the page works.

**Comment by e00E** [comment]
This is an error in the test with the new philosophy of not supporting python < 2.6 . The test explicitly tests python 2.5.5. I think the test should be removed.

**Comment by nathanielmanistaatgoogle** [comment]
Change content now looks great. Please squash commits (so that this pull request just has one commit) and adhere to http://chris.beams.io/posts/git-commit/#seven-rules with your commit message.

Thanks for this improvement!

**Comment by e00E** [comment]
Thank you too for reviewing

**Comment by nathanielmanistaatgoogle** [comment]
Passes my review. @tmatsuo do you want to be a second pair of eyes on this?

**Comment by tmatsuo** [comment]
LGTM

**Pull request merged**
