### PR TITLE
be completed if the HTTP status 200 is responded for range request.

### PR DESCRIPTION
**Pull request by crkz**
The current implementation is checking for transferred progress of total size to completion judgment.
will prevent an infinite loop of the case that are not contain both "Content-Range" and "Content-Length" is  in the response.

### CODE REVIEW

**Comment by crkz** [comment]
CLA signed.

**Comment by nathanielmanistaatgoogle** [comment]
Why was this closed?

**Comment by crkz** [comment]
I've signed with another email address... I made another p-r with appropriate one.

**Comment by nathanielmanistaatgoogle** [comment]
Understood. In the future, there's no need for that, because that sort of problem can be corrected inside an open pull request. :-)

**Comment by crkz** [comment]
Thanks for your advice, noted!

**Pull request closed without merging**
