### PR TITLE
Added new example to the Search Console sample

### PR DESCRIPTION
**Pull request by haymigoogle**

### CODE REVIEW

**Comment by haymigoogle** [comment]
I am a Google employee signed with my google email, what should I do to get the cla flag on?
Thanks.

**Comment by haymigoogle** [comment]
I linked the commit with my google email this time. Does it work out now?

**Comment by nathanielmanistaatgoogle** [comment]
Take a look at your author and committer information (`git log --pretty=fuller`) - they're showing an email address that probably isn't the email address you want associated with your commit.

**Comment by haymigoogle** [comment]
It wasn't at first, but I changed it. This is what I got:
Author:     Haymi Shalom <haymi@google.com>
AuthorDate: Sun Apr 3 15:54:50 2016 +0300
Commit:     Haymi Shalom <haymi@google.com>
CommitDate: Sun Apr 3 15:54:50 2016 +0300
Do you see something else? 

Thanks

**Comment by nathanielmanistaatgoogle** [comment]
Yes, I see something else.

Let's make sure we're talking about the same thing though: I'm looking at [31669ef82c70517a](https://github.com/haymigoogle/google-api-python-client/commit/31669ef82c70517a51ae27c4683f68a209a20cf3) which is what I currently see at the head of [your fork's master branch](https://github.com/haymigoogle/google-api-python-client/commits/master).

Note the text "@haymigoogle wants to merge 1 commit into google:master from haymigoogle:master" at the top of this page - what matters is what you've pushed to your fork on GitHub, and this may not be the same as what you're seeing on your local machine.

**Comment by haymigoogle** [comment]
Hope this works out now :)

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the change!

**Pull request merged**
