### PR TITLE
Release v1.5.1

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Now's as good a time as any to ask: what needs to be done to update [these docs](http://google.github.io/google-api-python-client/docs/epy/index.html) which somehow missed 1.5.0?

**Comment by jonparrott** [comment]
I'll need to separately update the gh-pages branch. sigh.

**Comment by nathanielmanistaatgoogle** [comment]
Looks great; thank you. Anything necessary before merging this?

**Comment by jonparrott** [comment]
Just needed your LGTM.

Merging, will push release once I'm in the office.

**Pull request merged**
