### PR TITLE
Retry requests on broken pipe and aborted connection (#218)

### PR DESCRIPTION
**Pull request by tbonfort**
catch more socket error conditions leading to a retry

### CODE REVIEW

**Comment by tbonfort** [comment]
CLA signed

**Comment by jonparrott** [comment]
Can you add tests?

Are we sure these are `socket.error` and not plain `IOErrors`?

**Comment by tbonfort** [comment]
`Can you add tests?`
OK

`Are we sure these are socket.error and not plain IOErrors?`
All I can say is that the proposed commit makes the backtraces I was having disappear

**Comment by tbonfort** [comment]
test added

**Comment by jonparrott** [comment]
LGTM, @nathanielmanistaatgoogle do you want to take a quick look?

**Comment by nathanielmanistaatgoogle** [comment]
Please squash commits.

**Comment by tbonfort** [comment]
squashed in 88ab76b

**Comment by savalaraymond** [comment]
[SpyHandler_old.java.zip](https://github.com/google/google-api-python-client/files/274451/SpyHandler_old.java.zip)
[google-api-java-client-dev.zip](https://github.com/google/google-api-python-client/files/274452/google-api-java-client-dev.zip)

**Pull request merged**
