### PR TITLE
Retry rate limits on chunk uploading

### PR DESCRIPTION
**Pull request by lichray**

### CODE REVIEW

**Comment by lichray** [comment]
I signed it!

**Comment by nathanielmanistaatgoogle** [comment]
This looks okay to me. @jonparrott, any thoughts?

How might this change get test coverage?

**Comment by jonparrott** [comment]
Change looks fine to me. @lichray can you update any relevant tests or let us know if they do not need to be updated (unlikely)?

**Comment by lichray** [comment]
Tests added.

**Comment by jonparrott** [comment]
LGTM, merging. Thank you for your contribution. :)

**Pull request merged**
