### PR TITLE
Correct the help description for the project_id argument of argparse

### PR DESCRIPTION
**Pull request by j450h1**
Corrected the help description for the project_id argument of argparse

### CODE REVIEW

**Comment by j450h1** [comment]
I signed it!

**Comment by nathanielmanistaatgoogle** [comment]
Please conform to [these guidelines](http://chris.beams.io/posts/git-commit/#seven-rules) in your commit message - in particular, "Update prediction.py" isn't a very informative subject line (there's probably space in fifty characters to mention that you are correcting a defect) and your non-subject-line text may be too long and is missing a period at the end.

Thank you for the fix!

**Comment by j450h1** [comment]
Thanks for the feedback. I'll close and start a new pull request with the proper commit message.

**Comment by j450h1** [comment]
Thanks for

**Comment by nathanielmanistaatgoogle** [comment]
There was no need to close this. :-(

**Pull request closed without merging**
