### PR TITLE
Sheets API with Examples using google-auth

### PR DESCRIPTION
**Pull request by Barathwaja**
Added Sheets API using latest google-auth library since oauth2client is being deprecated.
This example uses Service Account (json file). It consist of two basic example.

### CODE REVIEW

**Comment by jonparrott** [comment]
Hi @Barathwaja, thank you for doing this but I don't think this is the appropriate place for these samples.

**Comment by Barathwaja** [comment]
Hi @jonparrott , ok so where should I PR this then Coz you only mentioned that this is the correct place to PR. please refer the [PR](https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/235)

**Comment by grant** [comment]
Please create an issue before sending a PR.

There are lots of sheets examples here:
https://github.com/gsuitedevs/browser-samples

**Comment by Barathwaja** [comment]
@jonparrott which you couldn't said directly.
@grant so I can submit an issue and send a PR in the link you gave? Mine is Python script connecting to Sheets API

**Comment by grant** [comment]
@Barathwaja We already have a sample for python + Sheets, so I don't think we need a new one. I don't know what this PR is solving.

Please create an issue before a PR.

**Comment by Barathwaja** [comment]
@grant plain and simple python libraries used by google is deprecated which google has said before and there is not a clear example of using python google sheet api with new libraries. And the documentation in Sheet API using python is outdated one.

**Pull request closed without merging**
