### PR TITLE
Changes for the release 1.4.2.

### PR DESCRIPTION
**Pull request by tmatsuo**
Bumped the version number and added an entry in CHANGELOG.

I will appreciate if @nathanielmanistaatgoogle or @craigcitro can take a look.

### CODE REVIEW

**Comment by craigcitro** [comment]
I think you need to update the docs, too. (Maybe this is `tox -e docs`?)

**Comment by tmatsuo** [comment]
I see. I think this is `make docs`. Let me know if I'm doing wrong.

**Comment by nathanielmanistaatgoogle** [comment]
Also please follow the pattern of https://github.com/google/google-api-python-client/commits/eee38fa9d5e67df28bbb7f9321f - one commit for the change to `__init__.py`, one commit for the docs, and then one commit for the `CHANGELOG` change.

**Comment by tmatsuo** [comment]
Split it to 3 commits. PTAL

**Comment by craigcitro** [comment]
ah, right, we converted google/oauth2client to sphinx but not this repo.

LGTM.

**Comment by tmatsuo** [comment]
Maybe I can update the Makefile to use twine to upload to pypi. Also how about to add wheel distribution?

**Comment by craigcitro** [comment]
+1 on wheels.

On Fri, Sep 11, 2015 at 2:20 PM, Takashi Matsuo <notifications@github.com>
wrote:

> Maybe I can update the Makefile to use twine to upload to pypi. Also how
> about to add wheel distribution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/google-api-python-client/pull/134#issuecomment-139663599>
> .
>



-- 

-cc

**Comment by tmatsuo** [comment]
Changed the Makefile to use twine and added wheel distribution. PTAL.

**Comment by craigcitro** [comment]
lgtm -- i'll let @nathanielmanistaatgoogle merge.

**Comment by tmatsuo** [comment]
Let me add one more change before merge

**Comment by tmatsuo** [comment]
Ok, I just added --universal flag to the bdist-wheel command so that the generated package can be used with either of Python 2 or 3.

**Comment by tmatsuo** [comment]
OK. Sorry for the last minutes updates. I think it's really ready. @nathanielmanistaatgoogle PTAL and merge if looks good. Thx!

**Comment by nathanielmanistaatgoogle** [comment]
Looks great; merging.

Thanks for joining the team!

**Comment by pferate** [comment]
I added the content of docs to the gh-pages branch in PR #144

**Pull request merged**
