### PR TITLE
Release v1.6.0

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by jonparrott** [comment]
@lukesneeringer @landrito FYI, the docs update produces a ton of changes. It might be easier to review commit-by-commit so you can just see the changelog/version update.

**Comment by landrito** [comment]
The main README needs to be updated to denote the drop of 2.6.

**Comment by jonparrott** [comment]
> The main README needs to be updated to denote the drop of 2.6.

Done.

**Comment by jonparrott** [comment]
@lukesneeringer it's a good idea, but let's not tie it to this release? (I can likely configure it next week)

**Comment by jonparrott** [comment]
I'm going to go ahead and cut this release, adding testing for 3.5 shouldn't necessitate a new release (just some updated docs).

**Pull request merged**
