### PR TITLE
Add pyopenssl dependency

### PR DESCRIPTION
**Pull request by glefait**

### CODE REVIEW

**Comment by glefait** [comment]
Hello bot, I signed it!


2017-06-06 12:44 GMT-04:00 googlebot <notifications@github.com>:

**Comment by jonparrott** [comment]
Can we get some context here? What's the purpose of this change?

**Comment by glefait** [comment]
When using the python sample from the Reporting API v4 : https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-py, that library is required. 
It is already marked as required for developement, however if used in sample it makes sense to add it as a requirement or to edit the reporting doc to formalize that requirement.

**Comment by jonparrott** [comment]
Hmm.. this shouldn't require pyopenssl. oauth2client (while deprecated) has
pure-python support for cryptography. Which version of oauth2client do you
have?

**Comment by glefait** [comment]
Here's my python version
```
$ python --version
Python 3.5.3
```
And the dependencies after I installed pyopenssl (which installed cryptography)
```
$ pip freeze
asn1crypto==0.22.0
cffi==1.10.0
cryptography==1.9
google-api-python-client==1.6.2
httplib2==0.10.3
idna==2.5
oauth2client==4.1.0
pyasn1==0.2.3
pyasn1-modules==0.0.9
pycparser==2.17
pyOpenSSL==17.0.0
rsa==3.4.2
six==1.10.0
uritemplate==3.0.0
```

**Comment by jonparrott** [comment]
@glefait can you give me the full stacktrace of the error if you don't have `pyopenssl` installed?

**Comment by glefait** [comment]
@jonparrott yup, here's a new env:

```
virtualenv env
source env/bin/activate
pip install --upgrade google-api-python-client
# I edit the sample to replace print with print() and default key/email with mine

python sample.py 
Traceback (most recent call last):
  File "sample.py", line 85, in <module>
    main()
  File "sample.py", line 80, in main
    analytics = initialize_analyticsreporting()
  File "sample.py", line 32, in initialize_analyticsreporting
    SERVICE_ACCOUNT_EMAIL, KEY_FILE_LOCATION, scopes=SCOPES)
  File "/home/glefait/workspace/test-ga/env/lib/python3.5/site-packages/oauth2client/service_account.py", line 334, in from_p12_keyfile
    token_uri=token_uri, revoke_uri=revoke_uri)
  File "/home/glefait/workspace/test-ga/env/lib/python3.5/site-packages/oauth2client/service_account.py", line 289, in _from_p12_keyfile_contents
    raise NotImplementedError(_PKCS12_ERROR)
NotImplementedError: 
This library only implements PKCS#12 support via the pyOpenSSL library.
Either install pyOpenSSL, or please convert the .p12 file
to .pem format:
    $ cat key.p12 | \
    >   openssl pkcs12 -nodes -nocerts -passin pass:notasecret | \
    >   openssl rsa > key.pem
```
By the way, there is also a discrepency between the doc (https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/service-py#4_run_the_sample)

> Move the previously downloaded client_secrets.p12 to the same directory as the sample code.

and the replace_me info in the python file:

> KEY_FILE_LOCATION = '<REPLACE_WITH_JSON_FILE>'

**Comment by jonparrott** [comment]
I see, the issue here is that we no longer recommend .p12 keys, instead, we recommend .json keyfiles. The tutorial itself should be updated to use .json keys which do not require pyopenssl.

**Pull request closed without merging**
