### PR TITLE
Minor Markdown Fix

### PR DESCRIPTION
**Pull request by mmattioli**
Proposal
===

Update the copyright years on some files to 2015. Update some .md files to use better header formatting.

Reasoning
===

The nature of this PR should be self-explanatory but, just incase, we are currently in the year 2015 and the copyright years should reflect such as this is still an active project. The header style change in the .md files preserves the intended visual but uses a more easily editable method (no one wants to keep typing === under every letter of the header).

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
The markdown change looks righteous but I'll have to ask my colleagues about changing the copyright notices.

**Comment by mmattioli** [comment]
:+1:

**Comment by mmattioli** [comment]
@nathanielmanistaatgoogle just wondering what the status of this is. Thanks.

**Comment by dberlin** [comment]
Engilawyer here.
While we appreciate you taking the time to do this, updating copyright years is actually not legally required, and doesn't legally achieve anything (it's essentially cargo cult lawyering).  The date of first publication is clearly valid, and using other dates is actually "risky" (IE adding more dates could make your copyright notice invalid, even though it's common practice).
So we'd rather avoid the churn.

It's true that some people use copyright notices as a proxy for "how out of date something is", but that'll never change unless people stop updating them pointlessly each year :)

**Comment by nathanielmanistaatgoogle** [comment]
Thank you @dberlin.

@mmattioli: please reform this pull request to include just the documentation improvements and thank you for your contribution.

**Comment by mmattioli** [comment]
@nathanielmanistaatgoogle I just reverted in 3b5096d488a9f01fc6e85c569a37c9f31bca3741. This PR now includes only the doc fixes

**Comment by mmattioli** [comment]
@nathanielmanistaatgoogle I just committed with the documentation improvements only. Thanks!

**Pull request merged**
