### PR TITLE
Add Search Console (f.k.a Webmaster Tools) command line samples.

### PR DESCRIPTION
**Pull request by shlomifruchter**
1. Create directory Search Console API samples.
2. Add sample for Search Analytics API method (part of Search Console API).

### CODE REVIEW

**Comment by ashleyjelks** [comment]
I signed it!

**Comment by nathanielmanistaatgoogle** [comment]
Did you sign the CLA under a different account than the account with which you authored the commits and pull request? I'm still seeing the "cla: no" label here.

**Comment by shlomifruchter** [comment]
Hi, I'm a Google employee.

How should I sign the form?

**Comment by soltanmm** [comment]
IIRC the @googlebot's [link](https://cla.developers.google.com/) should work for any Google account, including your usual work account. Just be prepared to associate your GitHub account with your work account if you do that! Alternatively, use a second account.

**Pull request closed without merging**
