### PR TITLE
Set default timeout for all the HTTP requests

### PR DESCRIPTION
**Pull request by i-maravic**
This will avoid having hanging connections when using Google API calls.

In case the user have set default socket timeout, that value is used instead of default.

### CODE REVIEW

**Comment by i-maravic** [comment]
I signed it!

**Comment by i-maravic** [comment]
@fabriziodemaria

**Comment by i-maravic** [comment]
@jonparrott Could you take a look at this PR please?

**Comment by jonparrott** [comment]
5 minutes seems way too high. App Engine will terminate requests after 60 seconds.

**Comment by i-maravic** [comment]
@jonparrott I wanted to be conservative.

I've changed it to 60s now.

**Comment by jonparrott** [comment]
@i-maravic I guess my concern here is that I don't like the idea of using any library-specific timeout that the user doesn't explicitly set. It's surprising behavior. What prompted this change? Can I get some more context to better understand what problem this is trying to solve?

**Comment by i-maravic** [comment]
@jonparrott We're using google-api-python-client when running periodic (hourly or daily) batch jobs for uploading to BigQuery and reading/writing to Google Cloud Storage. All the periodic jobs are being executed in Docker containers.

Recently we've experienced issues with those jobs hanging forever without making any progress. After doing some investigation we detected that the code making requests to Google APIs (aka. google-api-python-client) is hanging forever while waiting something to read from TCP socket. This was surprising behaviour for us.

After doing even more digging we discovered that Docker had some weird networking issues, which were causing this in the first place. We're not 100% sure how to reproduce Docker issue though, but restarting the Docker service mitigated a lot of problems we're experiencing.

I fell that library doing HTTP requests should set a sane default timeout for doing HTTP requests, because we could easily avoid issues like this in the future. I would argue that this is what most of the users would like to have any how.

I would also like to point out that you already have code in your lib, which is dealing with Timeout exceptions that might be thrown from the HTTP requests and do the retries accordingly.

I know that you're not using _requests_ library, but there is very nice [explanation](http://docs.python-requests.org/en/master/user/quickstart/#timeouts) why all production code using it should set timeouts for all the HTTP requests it's doing.

**Comment by jonparrott** [comment]
@i-maravic I see, okay.

I need the CLA bot to verify your signature status before I can merge.

**Comment by i-maravic** [comment]
I work for Spotify. Spotify should have signed the CLA.

**Comment by jonparrott** [comment]
@i-maravic gotcha.

@lukesneeringer @landrito I'd appreciate if one of you could chime in and let me know your thoughts before I merge this.

**Comment by lukesneeringer** [comment]
A 60 second default timeout seems reasonable to me, and it is easy enough to override. LGTM.

**Comment by jonparrott** [comment]
@lukesneeringer thanks for chiming in!

@i-maravic okay, so it looks like this is going to happen, can I ask two things of you:

1. Is it possible to add tests or assertions to existing tests to cover this?
2. This timeout only applies to the http object used to fetch discovery documents. Do you want to apply the timeout to the http object used to make actual API requests as well?

**Comment by i-maravic** [comment]
@jonparrott Sounds like reasonable asks.

Could you point me out where is the http object for actual API requests constructed?

**Comment by jonparrott** [comment]
@i-maravic just below in `build_from_document`: https://github.com/google/google-api-python-client/pull/320/files#diff-bceb3b293cf7c789403d137d70ef8dd3R370

**Comment by i-maravic** [comment]
@jonparrott Now the default timeout is applied to all discovery and API requests (auth or not)

Hopefully I didn't miss and httplib2.Http() instantiation in the lib

**Comment by jonparrott** [comment]
@i-maravic this looks good, one last question:

Do you want to pass in `timeout` to `authorized_http` [here](https://github.com/google/google-api-python-client/pull/320/files#diff-bceb3b293cf7c789403d137d70ef8dd3R369)? Otherwise, the authorized http instance won't have the timeout.

**Comment by i-maravic** [comment]
@jonparrott `authorized_http` gets timeout set [here](https://github.com/google/google-api-python-client/pull/320/files#diff-39e7a8494b350ee804d3775fae23de87R88)

**Comment by jonparrott** [comment]
@i-maravic gotcha. Alright, this LGTM. Thanks!

**Pull request merged**
