### PR TITLE
Release v1.5.0

### PR DESCRIPTION
**Pull request by jonparrott**
@nathanielmanistaatgoogle @tmatsuo PTAL.

### CODE REVIEW

**Comment by tmatsuo** [comment]
LGTM except for one comment

**Comment by jonparrott** [comment]
> This commit looks behaviorally interesting and non-trivial

A few things:
* It's pretty trivial. There are some APIs that are returned by the discovery endpoint that do not yet have published discovery docs. This will try to build those APIs anyway and explode. The APIs that cause this aren't public yet and therefore should not be part of the public documentation.
* It does not change behavior; if anything, it ensures that the current behavior is maintained despite a change in expectations from the discovery service.
* This change is in our docs building tool and not the library itself.

**Comment by jonparrott** [comment]
> Please maintain no-blank-line-between-doc-string-and-behavior-body in this codebase?

Fixed.

**Comment by nathanielmanistaatgoogle** [comment]
Looks good and thanks for the release. :-)

**Comment by jonparrott** [comment]
Thanks, @nathanielmanistaatgoogle. :)

**Comment by jonparrott** [comment]
Published to [PyPI](https://pypi.python.org/pypi/google-api-python-client). #190 has been opened to both automate and document this process in the future.

**Pull request merged**
