### PR TITLE
Updates httplib2 link

### PR DESCRIPTION
**Pull request by originell**
just a small update as they moved the httplib2 project to it's own github user.

### CODE REVIEW

**Comment by jonparrott** [comment]
Hi @originell, thanks for the fix. I'm happy to merge this once you make googlebot happy.

**Comment by jonparrott** [comment]
Closing due to inactivity. Feel free to comment if you want to re-open it.

**Comment by originell** [comment]
Completely forgot about this. I signed it! :)

**Comment by jonparrott** [comment]
Thanks, @originell!

**Pull request merged**
