### PR TITLE
Release v1.5.4

### PR DESCRIPTION
**Pull request by jonparrott**

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Am I reading the test results correctly as indicating that we're not yet compatible with `oauth2client` 4.0.0?

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle apparently not! :D I'll have to revisit this later.

**Comment by nathanielmanistaatgoogle** [comment]
Understood; thanks.

**Comment by jonparrott** [comment]
@nathanielmanistaatgoogle this is fixed now and should be good to merge. The only tricky bit is that file_cache depended on locked_file, which we removed. The cache stuff was already well-guarded against failure, but the tests were not.

**Pull request merged**
